"""Activity router — read-only list + detail endpoints (VAL-ACTIVITY-009).

Activity entries are auto-generated by ``IssueService`` on issue mutations, so
this router exposes **no** create/update/delete endpoints — clients cannot
author free-text activity (the feed is system-generated only).
"""

import uuid
from typing import cast

from fastapi import APIRouter, Depends, Query, status
from fastapi_pagination import Page, Params

from app.core.logging import log_action, log_entity
from app.modules.activity.dependencies import get_activity_service
from app.modules.activity.filters import ActivityFilter
from app.modules.activity.schemas import ActivityResponse
from app.modules.activity.service import ActivityService
from app.user.auth import require_current_user_id

activity_router = APIRouter(
    prefix="/activity",
    tags=["activity"],
    dependencies=[Depends(require_current_user_id)],
)


@activity_router.get(
    "",
    response_description="List activity",
    status_code=status.HTTP_200_OK,
)
async def list_activity(
    pagination: Params = Depends(),
    activity_filter: ActivityFilter = Depends(),
    issue_id: uuid.UUID | None = Query(
        default=None,
        description="Restrict to activity on this issue (used by the drawer feed)",
    ),
    team_id: uuid.UUID | None = Query(
        default=None, description="Restrict to a single team"
    ),
    order_by: list[str] | None = Query(
        default=None,
        description="Sort fields (prefix '-' for desc, e.g. -created_at)",
    ),
    user_id: uuid.UUID = Depends(require_current_user_id),
    service: ActivityService = Depends(get_activity_service),
) -> Page[ActivityResponse]:
    """List activity for the authenticated user's teams.

    Supports filtering by ``issue_id`` (the activity feed on an issue — used by
    the issue drawer) and ``team_id``. Defaults to newest-first so the most
    recently generated entry renders at the top (VAL-ACTIVITY-001,
    VAL-ACTIVITY-008).
    """
    log_action("list")
    # Override the filter's order_by — FastAPI's Depends() doesn't parse
    # list[str] fields from query params, so we extract order_by via Query().
    if order_by is not None:
        activity_filter.order_by = order_by
    result = await service.get_all_paginated(
        pagination_params=pagination,
        entity_filter=activity_filter,
        user_id=user_id,
        issue_id=issue_id,
        team_id=team_id,
    )
    return cast(
        "Page[ActivityResponse]",
        Page[ActivityResponse].model_validate(
            {
                "items": [ActivityResponse.model_validate(a) for a in result.items],
                "total": result.total,
                "page": result.page,
                "size": result.size,
                "pages": result.pages,
            }
        ),
    )


@activity_router.get(
    "/{activity_id}",
    response_description="Get activity by ID",
    status_code=status.HTTP_200_OK,
)
async def get_activity(
    activity_id: uuid.UUID,
    user_id: uuid.UUID = Depends(require_current_user_id),
    service: ActivityService = Depends(get_activity_service),
) -> ActivityResponse:
    """Get an activity entry by ID, enforcing the issue's team membership."""
    log_action("get")
    log_entity("activity", activity_id)
    result = await service.get_by_id(activity_id, user_id=user_id)
    return ActivityResponse.model_validate(result)
